CXX = g++
SRCXX = chromosome.cpp crossover.cpp csvparser.cpp elitism.cpp exporter.cpp fitness.cpp main-ga.cpp mutate.cpp tournament.cpp
EXE = programv0.8.exe
default:
	$(CXX) -o $(EXE) $(SRCXX) -lpthread
run:
	./$(EXE)
